apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: ecommerce
    version: {{ .Chart.AppVersion }}
spec:
  selector:
    app: redis-app
  ports:
    - port: 6379
      targetPort: 6379

