apiVersion: batch/v1
kind: Job
metadata:
  name: fastapi-migrations-{{ include "fastapi-helm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: ecommerce-migration
    version: {{.Chart.AppVersion}}
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: migration-container
          image: <DOCKER_IMAGE_URL>
          command: ['alembic', 'upgrade', 'head']
          envFrom:
            - secretRef:
                name: migration-secret-{{ include "fastapi-helm.fullname" . }}
      initContainers:
        - name: init-postgres-service
          image: postgres:10.17
          command: ['sh', '-c',
          'until pg_isready -h postgres-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local -p 5432;
          do echo waiting for database; sleep 2; done;']
      restartPolicy: OnFailure
  backoffLimit: 15