apiVersion: v1
kind: Service
metadata:
  name: ecommerce-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: ecommerce
spec:
  selector:
    app: ecommerce-app
  ports:
    - port: 5000
      targetPort: 5000

