apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secret
  namespace: fastapi-project
  labels:
    app: ecommerce
data:
  DATABASE_USERNAME: bXVrdWxtYW50b3No
  DATABASE_PASSWORD: bXVrdWwxMjM=
  DATABASE_HOST: cG9zdGdyZXMtc2VydmljZQ==
  DATABASE_NAME: c2FtcGxlZGI=